### ISSUE TITLE
error on python setup.py install

### ISSUE THREAD

**Issue by ddesmond** [cgwire/gazu-publisher#41]
mbp-dev:gazu-publisher des$ python setup.py install
error in gazupublisher setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in qtazu@git+https://github.com/cgwire/qtazu.git#egg=qtazu at @git+https://github.com/cgwire/qtazu.git#egg=qtazu

**Comment by LedruRollin** [comment]
Thx for your feedback ! 
This bug has been fixed, so it shouldn't be a problem anymore. The gazu publisher still remains WIP so let us know if the error persists. If you want to, we've also written a procedure of installation here to make things easier : https://gazu.cg-wire.com/publisher.html

**Comment by ddesmond** [comment]
ok! lets move on this one!
os x mojave, 10.14.6
pyside2 installed, pip from python27

mbp-dev:gazu-publisher des$ pip install https://github.com/cgwire/gazu-publisher.git --user
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting https://github.com/cgwire/gazu-publisher.git
  Using cached https://github.com/cgwire/gazu-publisher.git
  ERROR: Cannot unpack file /private/var/folders/my/nn47_t4d365fr1p3rj6p0r7r0000gn/T/pip-unpack-rrb_dW/gazu-publisher.git (downloaded from /private/var/folders/my/nn47_t4d365fr1p3rj6p0r7r0000gn/T/pip-req-build-ARbn8n, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /private/var/folders/my/nn47_t4d365fr1p3rj6p0r7r0000gn/T/pip-req-build-ARbn8n

**Comment by LedruRollin** [comment]
Can you try the command `pip install git+https://github.com/cgwire/gazu-publisher.git --user`, instead of `pip install https://github.com/cgwire/gazu-publisher.git --user` (add `git+` in front of the url) ?
The mistake is in our tutorial, it was corrected but the PR with the fix has not been merged yet, sry for that. Let me know if it worked !

**Comment by ddesmond** [comment]
pip install -U setuptools did the trick for me, after the git+https worked just fine in --user mode.
mac mojave 10.14.6, python27, apple python build, no brew
