### ISSUE TITLE
error on standalone run python __main__.py

### ISSUE THREAD

**Issue by ddesmond** [cgwire/gazu-publisher#42]
Traceback (most recent call last):
  File "__main__.py", line 8, in <module>
    from gazupublisher.views.MainWindow import MainWindow
ImportError: No module named gazupublisher.views.MainWindow

**Comment by LedruRollin** [comment]
Thx for your feedback !
Import errors can happen, but it's difficult to know what's the issue here without further investigation. With the procedure of installation we've written [here](https://gazu.cg-wire.com/publisher.html), this bug should not happen. However, the gazu publisher still remains WIP, so let us know if you still encounter the issue.

**Comment by ddesmond** [comment]
mbp-dev:gazu-publisher des$ pip install git+https://github.com/cgwire/gazu-publisher.git
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/cgwire/gazu-publisher.git
  Cloning https://github.com/cgwire/gazu-publisher.git to /private/var/folders/my/nn47_t4d365fr1p3rj6p0r7r0000gn/T/pip-req-build-gKoPX2
  Running command git clone -q https://github.com/cgwire/gazu-publisher.git /private/var/folders/my/nn47_t4d365fr1p3rj6p0r7r0000gn/T/pip-req-build-gKoPX2
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/my/nn47_t4d365fr1p3rj6p0r7r0000gn/T/pip-req-build-gKoPX2/setup.py'"'"'; __file__='"'"'/private/var/folders/my/nn47_t4d365fr1p3rj6p0r7r0000gn/T/pip-req-build-gKoPX2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/my/nn47_t4d365fr1p3rj6p0r7r0000gn/T/pip-pip-egg-info-UaUAWb
         cwd: /private/var/folders/my/nn47_t4d365fr1p3rj6p0r7r0000gn/T/pip-req-build-gKoPX2/
    Complete output (1 lines):
    error in gazupublisher setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in qtazu@git+https://github.com/cgwire/qtazu.git#egg=qtazu at @git+https://github.com/cgwire/qtazu.git#egg=qtazu
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by LedruRollin** [comment]
Thx for your interest, hope the publisher will help you ! 
I've never met your error, it may come from [an old version of setuptools](https://github.com/sdispater/pendulum/issues/187), can you try `pip install setuptools -U` ?

**Comment by ddesmond** [comment]
great! setup tools did the trick (os x, mojave, apple python build, no brew), who would think of it! :)

![image](https://user-images.githubusercontent.com/2397041/87809538-d9361200-c85b-11ea-84e2-5202ef2e7d22.png)

i supose we can close both issues as solved since standalone is what im looking for.
(writing houdini tools, im still stuck with frank on outputypes so i was wondering how you guys do it and check what im doing wrong) Thanks for bringing me back to proper path @LedruRollin !
@frankrousseau you have a very great X-ZU guy here :)
