### ISSUE TITLE
Blender 2.8: Window > Launch not available; register function missing

### ISSUE THREAD

**Issue by garyritchie** [cgwire/gazu-publisher#45]
Getting this error in the Blender console:

```
Warning! 'C:\Users\Gary\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\startup\gazupublisher\__init__.py' has no register function, this is now a requirement for registerable scripts
```

**Comment by LedruRollin** [comment]
Hi, thx for your time !
Unfortunately, the tool is not available on Windows yet. I mean, you can install it, but the UI gets very ugly and while it remains functional it's very much not useable. The doc is not clear about that, I'll make the change ASAP

That being said, you should still be able to launch it. Have you followed [our tutorial](https://gazu.cg-wire.com/publisher.html#blender) ? It seems like you try to directly import the gazu publisher at startup. However, the procedure gives an add-on to launch at start-up, and it's this add-on that loads the publisher (installed elsewhere than in the Blender start-up files). For more details see the tutorial.

Let us know if it helped !
